language:
- c
os:
- osx
- linux
compiler:
- clang
- gcc
script: travis_wait 60 make all
stages:
  - test
  - docker
  - name: deploy
    if: branch = master AND type = push AND fork = false
  - name: run
    if: branch = master AND type = push AND fork = false
jobs:
  include:
    - stage: docker
      sudo: required
      services: docker
      os: linux
      script:
        - docker build -t 01625347/sws2019 .
        - docker run 01625347/sws2019 make assemble
        - docker run 01625347/sws2019 make spike
        - docker run 01625347/sws2019 make qemu
        - docker run 01625347/sws2019 make boolector
        - docker run 01625347/sws2019 make btormc
        - docker run 01625347/sws2019 make grader
    - stage: deploy
      sudo: required
      services: docker
      os: linux
      script:
        - docker build -t 01625347/sws2019 .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push 01625347/sws2019
    - stage: run
      sudo: required
      services: docker
      os: linux
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker run 01625347/sws2019 make assemble
        - docker run 01625347/sws2019 make spike
        - docker run 01625347/sws2019 make qemu
        - docker run 01625347/sws2019 make boolector
        - docker run 01625347/sws2019 make btormc
        - docker run 01625347/sws2019 make grader
notifications:
  email: false
  slack: unisalzburg:QvIGytsSaOqBt81UQrQ6ObLe